<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/10/09 15:43:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
