<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/10/15 14:15:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
